apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  my-config.txt: |
    # sample config file
    param1 = value1
    param2 = value2
  param3: value3updated
  param4: value4
  param5: fifthValue
  param6: sixthValueBrandSpankinNew
