apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpaca
    env: prod
    ver: "1"
  name: alpaca-prod
spec:
  ports:
  - nodePort: 30101
    port: 8080
    protocol: TCP
  selector:
    app: alpaca
    env: prod
    ver: "1"
  type: LoadBalancer
