apiVersion: v1
kind: Service
metadata:
  labels:
    app: bandicoot
    env: test
    ver: "1"
  name: bandicoot-test
spec:
  ports:
  - nodePort: 30090
    port: 8080
    protocol: TCP
  selector:
    app: bandicoot
    env: test
    ver: "1"
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bandicoot-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: test
      ver: "1"
  template:
    metadata:
      labels:
        app: bandicoot
        env: test
        ver: "1"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: bandicoot-test
        ports:
        - containerPort: 8080
          protocol: TCP
