apiVersion: v1
kind: Service
metadata:
  labels:
    app: bandicoot
    env: test
    ver: "1"
  name: bandicoot-test
spec:
  ports:
  - nodePort: 30090
    port: 8080
    protocol: TCP
  selector:
    app: bandicoot
    env: test
    ver: "1"
  type: NodePort
